### ISSUE TITLE
How to convert Rethinkdb cursor to JSON?

### ISSUE THREAD

**Issue by vectorselector** [CubosTecnologia/rethinkdb-crystal#12]
Possibly stupid noob question here:

I've been struggling for 2 days to get anything but a {nice => hash} from the Rethinkdb driver.
I realize that this is probably a desirable format for internal Crystal lang manipulation,
but I am struggling for 2 days now to get a JSON output from my JSON data (which I can confirm is stored as JSON inside Rethinkdb.)
All what I see in the spec files doesn't help me at all, nor have I seen anything informative in the source code.

Any tips greatly appreciated.

**Comment by vectorselector** [comment]
Ok, so  I managed to do so by casting the QueryResult (or is it cursor?) as so:
`.raw.to_json`

(here is the complete query)
previewCard = r.table("cards").get(env.params.url["id"].to_s).run(db).raw.to_json

**Comment by vectorselector** [comment]
I still don't understand, and I'm having difficulties on the same solution for a similar query that happens to include a .limit(8) and a .filter() statement.

`morecards = r.table("card_catalog").filter({:done => true}).limit(8).run(db).raw.to_json
`
I get the following error:
no overload matches 'RethinkDB::Cursor#to_json' with type JSON::Builder
Overloads are:
 - Object#to_json(io : IO)
 - Object#to_json()

      to_json(json)
      ^~~~~~~

**Comment by lbguilherme** [comment]
The return value of the execution of a query can either be a `QueryResult`, or a `Cursor`. The `QueryResult` happens when the query return a single datum value and is not a stream of values. The `Cursor` is for when it is a stream of values.

For `QueryResult` you can do `...run(conn).raw.to_json`.
For `Cursor` you can do `...run(conn).to_a.map(&.raw).to_json`.

**Comment by vectorselector** [comment]
Thank you!
